import styles from "../styles/Home.module.css";
//import ManualHeader from "../components/ManualHeader";

import Header from "../components/Header";

import Head from "next/head";
import { Input } from "web3uikit";
import JoinPresale1 from "../components/JoinPresale1";
import { useMoralis } from "react-moralis";
import { useEffect, useState, Fragment } from "react";
import { Modal } from "../components/Modal";
import WorkingModal from "../components/WorkingModal";

export default function Home() {
  const hideModal = () => setShowModal(false);

  let [showModal, setShowModal] = useState(false);

  const { isWeb3Enabled, chainId } = useMoralis();

  const supportedChains = ["97"];
  return (
    <Fragment>
      <div className={styles.container}>
        <Head>
          <title>SNOW Presale</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        {isWeb3Enabled ? (
          <div>
            {supportedChains.includes(parseInt(chainId).toString()) ? (
              <div className="flex flex-row"></div>
            ) : (
              <div>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
            )}
          </div>
        ) : (
          <div>Please connect to a Wallet</div>
        )}

        <button
          className="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none font-medium text-sm rounded-lg px-5 py-5 text-center mr-5"
          onClick={() => setShowModal(true)}
        ></button>
        <WorkingModal isVisible={showModal} onClose={hideModal}></WorkingModal>
      </div>
    </Fragment>
  );
}
